### ISSUE TITLE
概要/担当名などを含めた検索

### ISSUE THREAD

**Issue by eggplants** [inaniwaudon/alternative-tsukuba-kdb#4]
![image](https://user-images.githubusercontent.com/42153744/114290248-1a8ce280-9ab9-11eb-9329-efebb1aa9b21.png)

https://web.archive.org/web/20210227020621/https://kdb.tsukuba.ac.jp/campusweb/campussquare.do?_flowExecutionKey=_c4C6FF56E-A867-A95F-F3D8-381B23F5F4A1_k601FADED-3060-E5F0-547D-63CD15D5D857

キーワードの検索範囲に「概要・シラバス・備考含む」や「担当教員含む」オプションがあると検索性が向上します。
本家宜しく「シラバス」を含める場合はシラバスのクロールが必要になりますので、除外しても良いと思います。

**Comment by inaniwaudon** [comment]
対応しました。
チェックボックスを入れると、教室・教員名・概要 を含んだ検索ができるようになります。
ご指摘の通り、シラバスはクロールが必要ですので今回は見送らせていただきました。

**Comment by eggplants** [comment]
ウオー　助かっています。
